### ISSUE TITLE
[Suggestion] Some options for argument-placeholder

### ISSUE THREAD

**Issue by Andre601** [SuperRonanCraft/AdvancedCustomMenu#11]
### First suggestion
Making it possible, that you can only use `%argument_[id]%` without any additional placeholder, if that isn't a thing already.

That way, you could use it for things like punish-gui, where argument 2 (`%argument_1%`) could be the reason....

A example: You type `/punish Andre_601 spam` and can choose in the opening GUI, what you want to do (mute, warn, kick or ban him).
If you then click on a item (in my example for muting him), ACM will then run `/mute %argument_0% 1h %argument_1%` Which results in `/mute Andre_601 1h spam`

### Second suggestion
Adding a way, that a argument-placeholder can contain mutliple words...
Like `%argument_1-5%` which would use the arguments 2 to 6.

That would be - again - usefull for a punish-gui, if you want to give a more detailed reason...
If possible, you could also add, that ACM will use all args after a certain one (Make the range infinite)
It could be something like `%argument_1+%` which tells ACM, to use all arguments from 2 and up....

**Comment by SuperRonanCraft** [comment]
Ah yeah, %argument_<id>% is a thing, it even supports players, it retrieves their name, you can also retrieve integers, string and offline players name.
As for %argument_<idFrom>-<idTo>% would be a great addition
Infinite arguments, mhh, do you mean like anything after the non-required arguments? Like if someone types "/acm open <menu> <argumentsRequired> <argumentsRandomStuff>"?

**Comment by Andre601** [comment]
I mean every argument after argument x

So that `/punish Andre_601 Griefing` will work but `/punish Andre_601 Girefing at the spawn` will work too

**Comment by SuperRonanCraft** [comment]
Ah alright, should be rather easy to add cause all the arguments are already given to the api, just a simple process to get it working

**Comment by SuperRonanCraft** [comment]
Seems like it's been added to the Api :)
