### ISSUE TITLE
Getting "Whoops! This menu no longer exists due to a reload"

### ISSUE THREAD

**Issue by Andre601** [SuperRonanCraft/AdvancedCustomMenu#12]
**Plugin Version**:
3.1.0

**Issue Type** (Files/Loading/Menus/Commands/etc):
Getting the message "Whoops! This menu no longer exists due to a reload!", even when the menu isn't open any longer.
This message doesn't appear on reload, as long as you don't open a menu.
Even when you closed the menu before the reload, does this message show up.

**Suggestion** (How it may be resolved):

**Comments** (Anything you'd like to add):

**Comment by SuperRonanCraft** [comment]
Oh yeahhhhhh, dang, i forgot to fix this on the last patch xD it happens only if a player opens an inventory, this was broken after I had to fix that player caching system, the way events work didn't allow me to delete a players cache due to some issues, lets see if I am able to do this again
