### ISSUE TITLE
Wiki link from spigot broken

### ISSUE THREAD

**Issue by ezeiger92** [SuperRonanCraft/AdvancedCustomMenu#13]
Sorry for breaking your issue format!

The wiki link on your [spigot page](https://www.spigotmc.org/resources/advancedcustomitemapi.49628/) takes you to a missing page (https://github.com/SuperRonanCraft/AdvancedCustomMenu/api). It should end in /wiki rather than /api to reach your current wiki (unless you can change that).

**Comment by SuperRonanCraft** [comment]
Thanks you very much for bringing this to my attention :)
I just happen to change the wiki for AdvancedCustomMenu a little while ago and never update the spigot page for the api :P
