### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheIntelloBox** [SuperRonanCraft/AdvancedCustomMenu#18]
On the console 👍 
https://hastebin.com/azicedetet.md

Using Java 8, Paper Spigot 1.12.2 and Linux.

**Comment by SuperRonanCraft** [comment]
I am not able to view the hastebin, try posting it on https://pastebin.com/ and I will be able to view it hopefully.

**Comment by TheIntelloBox** [comment]
https://pastebin.com/r6QxrnHJ
