### ISSUE TITLE
Adding a delay for the Menu-Item

### ISSUE THREAD

**Issue by Andre601** [SuperRonanCraft/AdvancedCustomMenu#2]
Just add a delay (maybe in seconds?) on which after join, the player should get the item...
That can prevent Item-overwrights from plugins like AuthMe, which clears the inv at join.
It never happened to me, bacause I use FastLogin, but people, that need to manually login, could have problems...

**Comment by SuperRonanCraft** [comment]
Definitely coming to the next patch :)

**Comment by SuperRonanCraft** [comment]
Seems like this was added ;)
