### ISSUE TITLE
text from command-handler posted "randomly"

### ISSUE THREAD

**Issue by Andre601** [SuperRonanCraft/AdvancedCustomMenu#22]
**Plugin Version:**
3.2.7

**Issue Type:**
I set the following messages in the click-handler:
![](https://i.imgur.com/iUcZ4fn.png)

But the text appears like that:
![](https://i.imgur.com/U1NWmCH.png)

**Comment by SuperRonanCraft** [comment]
Mhh, this must be caused by the synchronous command execution, I see why that is a bad practice, i will find a better solution for this issue

**Comment by SuperRonanCraft** [comment]
Also, a question, are messages sent randomly constantly, like every time you execute the Chandler it sends the messages randomly each time, or only every time you reload the plugin?

**Comment by Andre601** [comment]
Every time I click on it

**Comment by Andre601** [comment]
I guess it's fixed now.....
