### ISSUE TITLE
Are we able to open a ChestCommands menu ?

### ISSUE THREAD

**Issue by TheIntelloBox** [SuperRonanCraft/AdvancedCustomMenu#23]
Hello.

You'll not add the covnerter, so is there a way that we can open a ChestCommands menu that is already created ?

Thanks.

**Comment by SuperRonanCraft** [comment]
No, you must personally change the files over, please stop bugging me about this, I feel less inclined to add this as a feature, not everyone has that amount of time to add such feature that will likely never be used
