### ISSUE TITLE
Wrong description in wiki for Menu-Item

### ISSUE THREAD

**Issue by Andre601** [SuperRonanCraft/AdvancedCustomMenu#28]
**Plugin Version**:
4.1.3

**Issue Type**:
Wrong description in Wiki

**Error**:
The wiki explains the options `Item-Move` and `Item-Drop` as follows:
```
Should the player be able to NOT move the item in their inventory?
Should the player NOT be able to drop the Item?
```

However, these descriptions are wrong, since setting the options to true allows players to drop or move the item while having it set to false doesn't.

**Possible solution**:
Update the descriptions by simply removing the NOT from them.

**Comments/More info**:
Links to both entries:
https://github.com/SuperRonanCraft/AdvancedCustomMenu/wiki/Menu-Item#item-move
https://github.com/SuperRonanCraft/AdvancedCustomMenu/wiki/Menu-Item#item-drop

**Comment by SuperRonanCraft** [comment]
Fixed, thanks for letting me know ;)
