### ISSUE TITLE
[Suggestion] arguments for custom commands.

### ISSUE THREAD

**Issue by Andre601** [SuperRonanCraft/AdvancedCustomMenu#4]
# The Idea
Adding a way, to use arguments in a custom command, to for example open a menu with stats of another player, or make a Punish-GUI.

It could be like this:
```yaml
commands: 'stats; stat'
Argument:
  Enabled: true
  Required: false
  Type: Player
```
# Explanation
## Enabled
If set to true, then there can be a argument after the command itself.

## Required
If true, then the GUI will only open, if you add a argument after it.

## Type
Valid types are:
* **Player**: The arg needs to be a online player.
* **Text**: A simple text... Anything from A-Z and 0-9.
* **Number**: The arg need to be a number.

# Possible problems
One problem could be, that the placeholders won't work correctly.
One way to fix that, would be, to "surround" it with a custom placeholder, like `%target_<placeholder without %>%`
If no arg is given, then the placeholders would work like normal...

**Comment by SuperRonanCraft** [comment]
I like the idea of having a sneaky stats page where placeholders are based off a saved player rather than a live player, that wouldn't be to hard to add, only challenge here what exactly would `Text` do and what would `Number` do in this argument **Type**?

**Comment by Andre601** [comment]
You could maybe use it for a special placeholder like %arg% that can be used at different places.

F.e. if the type is number, that you can use it in the item-amount.... or in certain commands...
That way you could make some sort of "dynamic" shop.

You type `/shop [amount]` and it will show different items with the amount [amount]
When you rightclick it, then it will run the commands `eco take %player_name% %arg%` and `give %player_name% [item] %arg%`
[Item] would be the item, that you set there...

**Comment by SuperRonanCraft** [comment]
I think I can work something out, i like having a dynamic menu, making shops with player's choice of how many items they can buy and stuff. This might come in a much later release, maybe in 2.3.0, which isn't too far from now, as there's a ton of improvement that has already been done in the latest patches :)

**Comment by SuperRonanCraft** [comment]
Seems like this has been added in 3.0.0, only thing missing is requiring the argument or not, but because a menu that needs an argument that doesn't get an argument will just output the text, so some development must be done to be able to replace these arguments still with default values
