### ISSUE TITLE
Menu can still be opened through the menu-item

### ISSUE THREAD

**Issue by Andre601** [SuperRonanCraft/AdvancedCustomMenu#6]
The title says everything.

Even if I remove/negate the permission `advancedcustommenu.open.*` can I open the menu with the menu-item.

**Comment by SuperRonanCraft** [comment]
Fixed, apparently this permission was only checked with commands and now the menu-item, this part is now a lot smarter and you can now configure if the item should even be given if the player has no permission to this menu, and what message to send if the player doesn't have permission but is trying to open the menu with the item :)
